#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection is configured as a "301 Moved Permanently"

apt-get update
apt-get install -y nginx
sudo sed -i 's/80 default_server/80/g' /etc/nginx/sites-available/default
echo "Holberton School" | sudo tee /var/www/html/index.html
echo "Redirecting to another page..." | sudo tee /var/www/html/redirect_me.html
sudo bash -c 'echo "
 server {
    listen 80;
    seqrver_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/redirect_me'
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/
sudo /etc/init.d/nginx restart
